app = "swillgram"
primary_region = "fra"

[build]
  [build.args]
    PYTHON_VERSION = "3.11"

[env]
  FLASK_ENV = "production"
  SECRET_KEY = "swillgram-super-secret-key-2024"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    restart_limit = 0