[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "gunicorn --worker-class eventlet -w 1 main:app"

[start]
cmd = "gunicorn --worker-class eventlet -w 1 main:app"